### ISSUE TITLE
Escape chars not being considered

### ISSUE THREAD

**Issue by Utodev** [DjMorgul/DRT#2]
I can't find in the code where the escape chars like #t or #n are replaced in DRT. Looking at that, I believe they are being considered like two different characters '#' followed by some other. Also replacementes from #A to#P are missing.

The replaceChars() function in drp.php from the DRC project makes all those substitutions. Replacement of Spanish characters is performed in DRT, but escape sequences are not. Also, drb does now support other international characters, which DRT does not replace either. They are replaced in a specific way in the same replaceChars() function.

May you please have  a look at both of them?
Thanks!

**Comment by DjMorgul** [comment]
@Utodev solved this in DRC (in the front-end, drf), by generating the JSON with all these escape sequences on the text strings already replaced for their correct character codes.
